name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualizaci칩n de v2 a v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3  # Actualizaci칩n de v2 a v3
      with:
        dotnet-version: '8.0.x'  # Cambiamos a .NET 8.0.x o la versi칩n m치s reciente disponible

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
